### ISSUE TITLE
Link to live demo redirects to an '503 Service Temporarily Unavailable' page

### ISSUE THREAD

**Issue by georgelappies** [javaeekickoff/java-ee-kickoff-app#10]
Seeing that this is 'THE DEFINITIVE' JSF template a working live demo link has high decision value for a new user contemplating using it. But if the link on the front README.md file is non functional it may create the impression that the rest of the template have non working parts as well; which may then deter a new user from trying it out; which of course would be a huge pity due to the awesomeness of this template. 

The site http://javaeekickoff.omnifaces.org/ from the links in the code redirects to an '503 Service Temporarily Unavailable' page

If the reason for this is due to bandwidth costs, please let me know and lets see how we may get it up again.

**Comment by BalusC** [comment]
Disk quota was full (hosted at OpenShift). 

Thanks.
