### ISSUE TITLE
@ViewScoped beans are not supported on stateless views.

### ISSUE THREAD

**Issue by jmfernandezg** [javaeekickoff/java-ee-kickoff-app#11]
The application was deployed to a Wildfly server. There is a strange issue regarding the form transient view.  The server's logged the following warning with every click made:

> WARNING [com.sun.faces.application.view.ViewScopeManager] (default task-49) @ViewScoped beans are not supported on stateless views
> [org.example.kickoff.view.phaselistener.FacesRequestLogger] (default task-49) GET={url=/contact, user={ip=127.0.0.1, login=null, session=UBhppmHYvdHzIXOJYEDUyGce3V_dUi2hDL6kch8G, viewState=null}, action={source=null, event=null, methods=[], validationFailed=false}, params={}, messages={j_id1=[@ViewScoped beans are not supported on stateless views]}, timer={0=91ms, 1=3ms, 2=-1ms, 3=-1ms, 4=-1ms, 5=-1ms, 6=87ms}}
> 
> 

It also appeared as a flash warning in the application:

![bug1](https://user-images.githubusercontent.com/28766453/29936684-af2c7a62-8e48-11e7-9989-69515702016a.png)

I checked /WEB-INF/tags/form.xhtml, and modified line 16:
`<f:view transient="#{stateless}">`

If I remove the transient property from the view the problem goes away. The stateless var evaluates to true because there is no user logged in. I interpret this as the correct intention, but I'm puzzled by the warning.

Thanks

**Comment by BalusC** [comment]
Which WF/Mojarra version exactly?

**Comment by BalusC** [comment]
Closing off due to lack of feedback and non-reproducible on latest WF/Mojarra as demonstrated on http://javaeekickoff.omnifaces.org
