### ISSUE TITLE
Fails to deploy caused by: java.lang.reflect.MalformedParameterizedTypeException on WildFly 11.0.0

### ISSUE THREAD

**Issue by zoperado** [javaeekickoff/java-ee-kickoff-app#17]
WFLYCTL0013: Operation ("read-attribute") failed - address: ([
    ("deployment" => "java-ee-kickoff-app.war"),
    ("subsystem" => "ejb3"),
    ("singleton-bean" => "BackgroundJobs")
]) - failure description: "WFLYEJB0370: EJB component for address [
    (\"deployment\" => \"java-ee-kickoff-app.war\"),
    (\"subsystem\" => \"ejb3\"),
    (\"singleton-bean\" => \"BackgroundJobs\")
] is in 
 state DOWN, must be in state UP"
21:35:14,900 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-7) WFLYJCA0019: Stopped Driver service with driver-name = java-ee-kickoff-app.war_org.h2.Driver_1_4
21:35:14,900 INFO  [org.jboss.as.jpa] (ServerService Thread Pool -- 29) WFLYJPA0004: Stopping Persistence Unit Service 'java-ee-kickoff-app.war#kickoff'
21:35:14,915 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 29) WFLYCLINF0003: Stopped java-ee-kickoff-app.war#kickoff.org.example.kickoff.model.User.loginTokens cache from hibernate container
21:35:14,915 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 29) WFLYCLINF0003: Stopped java-ee-kickoff-app.war#kickoff.org.hibernate.cache.internal.StandardQueryCache cache from hibernate container
21:35:14,915 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 29) WFLYCLINF0003: Stopped java-ee-kickoff-app.war#kickoff.org.hibernate.cache.spi.UpdateTimestampsCache cache from hibernate container
21:35:14,931 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-6) WFLYMAIL0002: Unbound mail session [java:app/kickoff/MailSession]
21:35:14,931 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-8) WFLYJCA0010: Unbound data source [java:app/kickoff/DataSource]
21:35:14,983 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0028: Stopped deployment java-ee-kickoff-app.war (runtime-name: java-ee-kickoff-app.war) in 76ms
21:35:14,984 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of "java-ee-kickoff-app.war" (runtime-name: "java-ee-kickoff-app.war")
21:35:15,987 INFO  [org.jboss.as.jpa] (MSC service thread 1-1) WFLYJPA0002: Read persistence.xml for kickoff
21:35:16,203 INFO  [org.jboss.weld.deployer] (MSC service thread 1-1) WFLYWELD0003: Processing weld deployment java-ee-kickoff-app.war
21:35:16,234 INFO  [org.jboss.as.ejb3.deployment] (MSC service thread 1-1) WFLYEJB0473: JNDI bindings for session bean named 'EmailLoader' in deployment unit 'deployment "java-ee-kickoff-app.war"' are as follows:

	java:global/java-ee-kickoff-app/EmailLoader!org.example.kickoff.business.email.EmailLoader
	java:app/java-ee-kickoff-app/EmailLoader!org.example.kickoff.business.email.EmailLoader
	java:module/EmailLoader!org.example.kickoff.business.email.EmailLoader
	java:global/java-ee-kickoff-app/EmailLoader
	java:app/java-ee-kickoff-app/EmailLoader
	java:module/EmailLoader

21:35:16,234 INFO  [org.jboss.as.ejb3.deployment] (MSC service thread 1-1) WFLYEJB0473: JNDI bindings for session bean named 'KickoffEmailService' in deployment unit 'deployment "java-ee-kickoff-app.war"' are as follows:

	java:global/java-ee-kickoff-app/KickoffEmailService!org.example.kickoff.business.email.KickoffEmailService
	java:app/java-ee-kickoff-app/KickoffEmailService!org.example.kickoff.business.email.KickoffEmailService
	java:module/KickoffEmailService!org.example.kickoff.business.email.KickoffEmailService
	java:global/java-ee-kickoff-app/KickoffEmailService
	java:app/java-ee-kickoff-app/KickoffEmailService
	java:module/KickoffEmailService

21:35:16,234 INFO  [org.jboss.as.ejb3.deployment] (MSC service thread 1-1) WFLYEJB0473: JNDI bindings for session bean named 'UserService' in deployment unit 'deployment "java-ee-kickoff-app.war"' are as follows:

	java:global/java-ee-kickoff-app/UserService!org.example.kickoff.business.service.UserService
	java:app/java-ee-kickoff-app/UserService!org.example.kickoff.business.service.UserService
	java:module/UserService!org.example.kickoff.business.service.UserService
	java:global/java-ee-kickoff-app/UserService
	java:app/java-ee-kickoff-app/UserService
	java:module/UserService

21:35:16,234 INFO  [org.jboss.as.ejb3.deployment] (MSC service thread 1-1) WFLYEJB0473: JNDI bindings for session bean named 'EmailTemplateService' in deployment unit 'deployment "java-ee-kickoff-app.war"' are as follows:

	java:global/java-ee-kickoff-app/EmailTemplateService!org.example.kickoff.business.email.EmailTemplateService
	java:app/java-ee-kickoff-app/EmailTemplateService!org.example.kickoff.business.email.EmailTemplateService
	java:module/EmailTemplateService!org.example.kickoff.business.email.EmailTemplateService
	java:global/java-ee-kickoff-app/EmailTemplateService
	java:app/java-ee-kickoff-app/EmailTemplateService
	java:module/EmailTemplateService

21:35:16,234 INFO  [org.jboss.as.ejb3.deployment] (MSC service thread 1-1) WFLYEJB0473: JNDI bindings for session bean named 'LoginTokenService' in deployment unit 'deployment "java-ee-kickoff-app.war"' are as follows:

	java:global/java-ee-kickoff-app/LoginTokenService!org.example.kickoff.business.service.LoginTokenService
	java:app/java-ee-kickoff-app/LoginTokenService!org.example.kickoff.business.service.LoginTokenService
	java:module/LoginTokenService!org.example.kickoff.business.service.LoginTokenService
	java:global/java-ee-kickoff-app/LoginTokenService
	java:app/java-ee-kickoff-app/LoginTokenService
	java:module/LoginTokenService

21:35:16,234 INFO  [org.jboss.as.ejb3.deployment] (MSC service thread 1-1) WFLYEJB0473: JNDI bindings for session bean named 'BackgroundJobs' in deployment unit 'deployment "java-ee-kickoff-app.war"' are as follows:

	java:global/java-ee-kickoff-app/BackgroundJobs!org.example.kickoff.business.BackgroundJobs
	java:app/java-ee-kickoff-app/BackgroundJobs!org.example.kickoff.business.BackgroundJobs
	java:module/BackgroundJobs!org.example.kickoff.business.BackgroundJobs
	java:global/java-ee-kickoff-app/BackgroundJobs
	java:app/java-ee-kickoff-app/BackgroundJobs
	java:module/BackgroundJobs

21:35:16,519 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-8) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.4)
21:35:16,535 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-5) WFLYJCA0018: Started Driver service with driver-name = java-ee-kickoff-app.war_org.h2.Driver_1_4
21:35:16,535 WARN  [org.jboss.as.connector.subsystems.datasources.AbstractDataSourceService$AS7DataSourceDeployer] (MSC service thread 1-3) IJ020016: Missing <recovery> element. XA recovery disabled for: java:app/kickoff/DataSource
21:35:16,535 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-5) WFLYMAIL0001: Bound mail session [java:app/kickoff/MailSession]
21:35:16,535 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) WFLYJCA0001: Bound data source [java:app/kickoff/DataSource]
21:35:16,551 INFO  [org.omnifaces.utils.properties.PropertiesUtils] (JCA PoolFiller) Loaded 2 settings from vfs:/C:/Users/User/wildfly/wildfly-11.0.0.Final/standalone/deployments/java-ee-kickoff-app.war/WEB-INF/classes/META-INF/omni-settings.xml.
21:35:16,551 INFO  [org.omnifaces.utils.properties.PropertiesUtils] (JCA PoolFiller) Loaded 4 settings from vfs:/C:/Users/User/wildfly/wildfly-11.0.0.Final/standalone/deployments/java-ee-kickoff-app.war/WEB-INF/classes/META-INF/conf/datasource-settings.xml.
21:35:16,551 INFO  [org.example.kickoff.config.DataSourceStagedPropertiesFileLoader] (JCA PoolFiller) 

About to install DataSource. 
Classname: org.h2.jdbcx.JdbcDataSource
URL: jdbc:h2:mem:kickoff;DB_CLOSE_DELAY=-1
21:35:16,588 INFO  [org.jboss.as.jpa] (ServerService Thread Pool -- 29) WFLYJPA0003: Starting Persistence Unit Service 'java-ee-kickoff-app.war#kickoff'
21:35:16,588 INFO  [org.hibernate.jpa.internal.util.LogHelper] (ServerService Thread Pool -- 29) HHH000204: Processing PersistenceUnitInfo [
	name: kickoff
	...]
21:35:16,797 WARN  [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool] (ServerService Thread Pool -- 29) IJ000407: No lazy enlistment available for java-ee-kickoff-app_java-ee-kickoff-app_java-ee-kickoff-app_java:app/kickoff/DataSource
21:35:16,797 INFO  [org.hibernate.dialect.Dialect] (ServerService Thread Pool -- 29) HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
21:35:16,834 INFO  [org.hibernate.envers.boot.internal.EnversServiceImpl] (ServerService Thread Pool -- 29) Envers integration enabled? : true
21:35:16,897 INFO  [org.hibernate.cache.spi.UpdateTimestampsCache] (ServerService Thread Pool -- 29) HHH000250: Starting update timestamps cache at region: java-ee-kickoff-app.war#kickoff.org.hibernate.cache.spi.UpdateTimestampsCache
21:35:16,897 INFO  [org.infinispan.expiration.impl.ExpirationManagerImpl] (ServerService Thread Pool -- 29) ISPN000025: wakeUpInterval is <= 0, not starting expired purge thread
21:35:16,897 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 29) WFLYCLINF0002: Started java-ee-kickoff-app.war#kickoff.org.hibernate.cache.spi.UpdateTimestampsCache cache from hibernate container
21:35:16,897 INFO  [org.hibernate.cache.internal.StandardQueryCache] (ServerService Thread Pool -- 29) HHH000248: Starting query cache at region: java-ee-kickoff-app.war#kickoff.org.hibernate.cache.internal.StandardQueryCache
21:35:16,897 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 29) WFLYCLINF0002: Started java-ee-kickoff-app.war#kickoff.org.hibernate.cache.internal.StandardQueryCache cache from hibernate container
21:35:16,950 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 29) WFLYCLINF0002: Started java-ee-kickoff-app.war#kickoff.org.example.kickoff.model.User.loginTokens cache from hibernate container
21:35:17,019 INFO  [org.hibernate.tool.schema.internal.SchemaCreatorImpl] (ServerService Thread Pool -- 29) HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@16d6e9c0'
21:35:17,019 INFO  [org.hibernate.hql.internal.QueryTranslatorFactoryInitiator] (ServerService Thread Pool -- 29) HHH000397: Using ASTQueryTranslatorFactory
21:35:17,432 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service jboss.deployment.unit."java-ee-kickoff-app.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."java-ee-kickoff-app.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1978)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:108)
	at java.lang.Class.getGenericInterfaces(Class.java:913)
	at org.jboss.weld.util.reflection.HierarchyDiscovery.discoverInterfaces(HierarchyDiscovery.java:143)
	at org.jboss.weld.util.reflection.HierarchyDiscovery.discoverFromClass(HierarchyDiscovery.java:139)
	at org.jboss.weld.util.reflection.HierarchyDiscovery.discoverTypes(HierarchyDiscovery.java:111)
	at org.jboss.weld.util.reflection.HierarchyDiscovery.<init>(HierarchyDiscovery.java:93)
	at org.jboss.weld.util.reflection.HierarchyDiscovery.<init>(HierarchyDiscovery.java:86)
	at org.jboss.weld.annotated.enhanced.TypeClosureLazyValueHolder.computeValue(TypeClosureLazyValueHolder.java:43)
	at org.jboss.weld.annotated.enhanced.TypeClosureLazyValueHolder.computeValue(TypeClosureLazyValueHolder.java:33)
	at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:49)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotated.getTypeClosure(BackedAnnotated.java:27)
	at org.jboss.weld.annotated.enhanced.jlr.AbstractEnhancedAnnotated.getTypeClosure(AbstractEnhancedAnnotated.java:203)
	at org.jboss.weld.util.Beans.getTypes(Beans.java:437)
	at org.jboss.weld.bean.attributes.BeanAttributesFactory$BeanAttributesBuilder.<init>(BeanAttributesFactory.java:113)
	at org.jboss.weld.bean.attributes.BeanAttributesFactory$BeanAttributesBuilder.<init>(BeanAttributesFactory.java:93)
	at org.jboss.weld.bean.attributes.BeanAttributesFactory.forBean(BeanAttributesFactory.java:70)
	at org.jboss.weld.bootstrap.AbstractBeanDeployer.createManagedBean(AbstractBeanDeployer.java:260)
	at org.jboss.weld.bootstrap.BeanDeployer.createClassBean(BeanDeployer.java:226)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$2.doWork(ConcurrentBeanDeployer.java:74)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$2.doWork(ConcurrentBeanDeployer.java:71)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

21:35:17,436 ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 1) WFLYCTL0013: Operation ("full-replace-deployment") failed - address: ([]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"java-ee-kickoff-app.war\".WeldStartService" => "Failed to start service
    Caused by: java.lang.reflect.MalformedParameterizedTypeException"}}
21:35:17,494 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 1) WFLYSRV0016: Replaced deployment "java-ee-kickoff-app.war" with deployment "java-ee-kickoff-app.war"
21:35:17,494 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0183: Service status report

**Comment by zoperado** [comment]
Just tried to see if other commits run on my env:  tried to run commit  bb3e4f7  and it does get me further indeed. Deploys just fine - just some issues with a taglib = "Warning: This page calls for XML namespace http://kickoff.example.org/ui declared with prefix k but no taglibrary exists for that namespace"

**Comment by zoperado** [comment]
It seems that the omnifaces upgrade (pon.xml) causes this.

**Comment by BalusC** [comment]
Kickoff app had been modified to target JSF 2.3. It would only work on a WF server (modded) with JSF 2.3. When deploying to WildFly with JSF 2.2, deployment will fail as above.

I've created separate branches now:

- [wildfly-jsf23](https://github.com/javaeekickoff/java-ee-kickoff-app/tree/wildfly-jsf23)
- [wildfly-jsf22](https://github.com/javaeekickoff/java-ee-kickoff-app/tree/wildfly-jsf22)
