### ISSUE TITLE
Test cases don't run / out of sync

### ISSUE THREAD

**Issue by zoperado** [javaeekickoff/java-ee-kickoff-app#18]
dbunit references not resolving.  Found that adding works 
`<dependency>
    <groupId>org.jboss.arquillian.extension</groupId>
    <artifactId>arquillian-persistence-dbunit</artifactId>
    <version>1.0.0.Alpha7</version>
    <scope>test</scope>
</dependency>
`
However, the test code is broken as it's not in symphony with the main code. Several classes need to be added and shrinkwrapped to make tests run again.

**Comment by BalusC** [comment]
Test cases have been caught up.
