### ISSUE TITLE
Update to OmniSecurity version to 0.6

### ISSUE THREAD

**Issue by haisi** [javaeekickoff/java-ee-kickoff-app#2]
Could you update the example to the newest version of OmniSecurity? It seems like there are a couple of differences.

**Comment by arjantijms** [comment]
The entire kickoff application is in desperate need of updating, certainly now that it's a year later. OmniSecurity is still largely an experimental library. I'll take a look at what's easier/better; update to latest OmniSecurity snapshot or incorporate the latest re-imagining of OmniSecurity as used by JSR 375 proposals.

**Comment by BalusC** [comment]
Already done during last updates.
