### ISSUE TITLE
Can't find resource for bundle java.util.PropertyResourceBundle

### ISSUE THREAD

**Issue by skaterkamp** [javaeekickoff/java-ee-kickoff-app#6]
I got a lot of Exceptions with Wildfly 10.1.0.Final in the server.log when running java-ee-kickoff-app:

FINEST [javax.enterprise.resource.webcontainer.jsf.resource] (default task-52) Ignoring missing resource: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key javax.faces.resource.localePrefix
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
        at java.util.ResourceBundle.getObject(ResourceBundle.java:444)
        at java.util.ResourceBundle.getString(ResourceBundle.java:407)
        at com.sun.faces.application.resource.ResourceManager.getLocalePrefix(ResourceManager.java:608)
....

Adding a line javax.faces.resource.localePrefix = ...  to each ApplicationBundle*.properties did fix it, see also

http://stackoverflow.com/questions/37708090/unable-to-find-or-serve-localized-resource-from-jsf-resource-library

Is it missing by intent here in java-ee-kickoff-app and the real cause for these exceptions is in Wildfly?

**Comment by BalusC** [comment]
FINEST is not an error. This is purely informal. A missing resource has just been ignored by Mojarra.

Adjust your logging level to DEBUG or higher.
