### ISSUE TITLE
AuthBacking and child violate @PostConstruct contract

### ISSUE THREAD

**Issue by ogregoire** [javaeekickoff/java-ee-kickoff-app#9]
The signature for `AuthBacking` and its child, `ResetPasswordBacking`, define a `@PostConstruct` method like this:

    @PostConstruct
    public void init() throws IOException

None of those classes are interceptors. So, for such classes, the [`@PostConstruct` Javadoc](http://docs.oracle.com/javaee/7/api/javax/annotation/PostConstruct.html) specify the following:

> The method defined on a non-interceptor class MUST HAVE the following signature:
>  `void <METHOD>()`

NetBeans shows errors when opening those classes because "`@PostConstruct` annotated method must not throw a checked exception." It compiles them properly, though.

Would it be possible to catch the potential `IOException` and wrap it in an `UncheckedIOException` to satisfy the spec?

**Comment by BalusC** [comment]
This is fixed in OmniFaces 3.0. I will update the kickoff app as soon as OmniFaces 3.0 is final.

See https://github.com/omnifaces/omnifaces/issues/338

**Comment by BalusC** [comment]
Updated now.
